/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author kas6570
 */
public class Main extends javax.swing.JFrame {
    ArrayList<Room> rooms = new ArrayList<Room>();
    int roomNumber;

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        meetingsDisplayChooserPanel = new javax.swing.JPanel();
        meetingsDisplayLabel = new javax.swing.JLabel();
        meetingsEntireDayButton = new javax.swing.JButton();
        meetingsSelectedRoomLabel = new javax.swing.JButton();
        meetingsSelectedUserLabel = new javax.swing.JButton();
        meetingsSpecificTimeSlotLabel = new javax.swing.JButton();
        roomPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomsList = new javax.swing.JList<>();
        addRoomButton = new javax.swing.JButton();
        removeRoomButton = new javax.swing.JButton();
        meetingPanel = new javax.swing.JPanel();
        addMeetingButton = new javax.swing.JButton();
        removeMeetingButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        meetingsList = new javax.swing.JList<>();
        personPanel = new javax.swing.JPanel();
        addPersonButton = new javax.swing.JButton();
        removePersonButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        peopleList = new javax.swing.JList<>();
        savePanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        saveAsButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        meetingsDisplayChooserPanel.setLayout(new java.awt.GridBagLayout());

        meetingsDisplayLabel.setText("Showing Meetings For: Entire Day");
        meetingsDisplayLabel.setHorizontalAlignment(SwingConstants.CENTER);
        meetingsDisplayLabel.setVerticalAlignment(SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        meetingsDisplayChooserPanel.add(meetingsDisplayLabel, gridBagConstraints);

        meetingsEntireDayButton.setText("Entire Day");
        meetingsEntireDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetingsEntireDayButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 48;
        meetingsDisplayChooserPanel.add(meetingsEntireDayButton, gridBagConstraints);

        meetingsSelectedRoomLabel.setText("Selected Room");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 20;
        meetingsDisplayChooserPanel.add(meetingsSelectedRoomLabel, gridBagConstraints);

        meetingsSelectedUserLabel.setText("Selected User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 28;
        meetingsDisplayChooserPanel.add(meetingsSelectedUserLabel, gridBagConstraints);

        meetingsSpecificTimeSlotLabel.setText("Specific Time Slot");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        meetingsDisplayChooserPanel.add(meetingsSpecificTimeSlotLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(meetingsDisplayChooserPanel, gridBagConstraints);

        roomPanel.setLayout(new java.awt.GridBagLayout());

        roomsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(roomsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 117;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        roomPanel.add(jScrollPane1, gridBagConstraints);

        addRoomButton.setText("Add Room");
        addRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        roomPanel.add(addRoomButton, gridBagConstraints);

        removeRoomButton.setText("Remove Room");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        roomPanel.add(removeRoomButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(roomPanel, gridBagConstraints);

        meetingPanel.setLayout(new java.awt.GridBagLayout());

        addMeetingButton.setText("Add Meeting");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        meetingPanel.add(addMeetingButton, gridBagConstraints);

        removeMeetingButton.setText("Remove Meeting");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        meetingPanel.add(removeMeetingButton, gridBagConstraints);

        meetingsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(meetingsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 95;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        meetingPanel.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(meetingPanel, gridBagConstraints);

        personPanel.setLayout(new java.awt.GridBagLayout());

        addPersonButton.setText("Add Person");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        personPanel.add(addPersonButton, gridBagConstraints);

        removePersonButton.setText("Remove Person");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        personPanel.add(removePersonButton, gridBagConstraints);

        peopleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(peopleList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 95;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        personPanel.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(personPanel, gridBagConstraints);

        savePanel.setLayout(new java.awt.GridBagLayout());

        saveButton.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 17;
        savePanel.add(saveButton, gridBagConstraints);

        saveAsButton.setText("Save As");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        savePanel.add(saveAsButton, gridBagConstraints);

        openButton.setText("Open");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        savePanel.add(openButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.3;
        getContentPane().add(savePanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void meetingsEntireDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetingsEntireDayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meetingsEntireDayButtonActionPerformed

    private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed
        try {
            roomNumber = Integer.parseInt(JOptionPane.showInputDialog("Hey"));
        } catch (Exception exception) {
            // NOT DONE
        }
        Room room = new Room(roomNumber);
        rooms.add(room);
        
        roomsList = new JList(rooms.toArray());
    }//GEN-LAST:event_addRoomButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMeetingButton;
    private javax.swing.JButton addPersonButton;
    private javax.swing.JButton addRoomButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel meetingPanel;
    private javax.swing.JPanel meetingsDisplayChooserPanel;
    private javax.swing.JLabel meetingsDisplayLabel;
    private javax.swing.JButton meetingsEntireDayButton;
    private javax.swing.JList<String> meetingsList;
    private javax.swing.JButton meetingsSelectedRoomLabel;
    private javax.swing.JButton meetingsSelectedUserLabel;
    private javax.swing.JButton meetingsSpecificTimeSlotLabel;
    private javax.swing.JButton openButton;
    private javax.swing.JList<String> peopleList;
    private javax.swing.JPanel personPanel;
    private javax.swing.JButton removeMeetingButton;
    private javax.swing.JButton removePersonButton;
    private javax.swing.JButton removeRoomButton;
    private javax.swing.JPanel roomPanel;
    private javax.swing.JList<String> roomsList;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel savePanel;
    // End of variables declaration//GEN-END:variables
}
