/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.io.Serializable;
import javax.swing.BorderFactory;
import javax.swing.border.EmptyBorder;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author kensch
 */
public class Person extends javax.swing.JPanel implements Serializable {

    private String firstName, lastName; // first and lastname of person
    private int phoneNumber;    // phonenumber of person
    // ******** cannot be at more than one meeting in any one-hour time slot

    /**
     * Creates new form Person
     */
    public Person(String firstName, String lastName, int phoneNumber) {
        initComponents();
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        personFirstName.setText(getFirstName());
        personLastName.setText(lastName);
        this.setBorder(BorderFactory.createCompoundBorder(new EmptyBorder(10, 10, 10, 10), new EtchedBorder()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        personFirstName = new javax.swing.JLabel();
        personLastName = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        personFirstName.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(personFirstName, gridBagConstraints);

        personLastName.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(personLastName, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public String toString() {
        return firstName + ' ' + lastName;
    }

    /**
     * @return the firstName
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * @param firstName the firstName to set
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return the lastName
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @param lastName the lastName to set
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return the phoneNumber
     */
    public int getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber the phoneNumber to set
     */
    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel personFirstName;
    private javax.swing.JLabel personLastName;
    // End of variables declaration//GEN-END:variables
}
